//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPB1.WebForms.Foton.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://RONY-PC:8080/B1iXcellerator/exec/soap/vP.0010000104.in_WCSX/com.sap.b1i.vp" +
            "latform.runtime/INB_WS_CALL_SYNC_XPT/INB_WS_CALL_SYNC_XPT.ipo/proc")]
        public string SAPB1_WebForms_Foton_WsFotonRamo_ipostep_vP_0010000104_in_WCSX_com_sap_b1i_vplatform_runtime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPT_ipo_proc_Service {
            get {
                return ((string)(this["SAPB1_WebForms_Foton_WsFotonRamo_ipostep_vP_0010000104_in_WCSX_com_sap_b1i_vplatf" +
                    "orm_runtime_INB_WS_CALL_SYNC_XPT_INB_WS_CALL_SYNC_XPT_ipo_proc_Service"]));
            }
        }
    }
}
